# Q1. What are the benefits of the built-in array package, if any?

Python does have a built-in array module which provides a low-level array data structure that is more memory-efficient than using regular Python lists for large amounts of numerical data. 
1) Memory Efficiency: The array module is designed to be memory-efficient, which can be particularly useful when dealing with large datasets. It stores data more compactly compared to lists, as it doesn't store additional information like list lengths and object references.
2) Performance: Operations on array objects can be faster than equivalent operations on lists because arrays store data in a more contiguous memory block, allowing for better cache utilization and potentially reducing memory access overhead.
3) Type Control: Arrays are constrained to holding elements of the same data type. This constraint ensures consistent data types and can be useful in scenarios where data type integrity is critical.
4) Interoperability: The array module is particularly useful when interfacing with low-level code or libraries that expect data to be in a certain format, such as C or Fortran libraries.
5) Interoperability: The array module is particularly useful when interfacing with low-level code or libraries that expect data to be in a certain format, such as C or Fortran libraries.

# Q2. What are some of the array package&#39;s limitations?

The "array package" in Python typically refers to the array module, which provides a basic array data structure. While the array module has its benefits, it also comes with some limitations.
rrays created using the array module can only store elements of a single data type. This restriction can be limiting when dealing with datasets that contain different data types.Arrays have a fixed size once they are created. You cannot easily add or remove elements from an array like you can with lists.The array module provides a basic set of operations.

# Q3. Describe the main differences between the array and numpy packages.

__array:__ The array module offers a basic array data structure with limited functionality. It is mainly designed for storing arrays of a single data type efficiently.he array module supports a limited set of basic data types such as integers and floats.he array module has a limited set of operations, mainly focused on basic array manipulation and element access.he array module is memory-efficient compared to Python lists, but it may not be as optimized for performance as NumPy.here array module provides one-dimensional arrays only.

__numpy:__ NumPy is a powerful numerical computing library that provides a multidimensional array object (numpy.ndarray). It offers a vast array of mathematical functions and operations, making it suitable for complex numerical computations, linear algebra, statistics, and more.NumPy arrays can hold a wide range of data types, including integers, floats, complex numbers, and even user-defined data types. This flexibility is crucial for scientific and numerical computing.NumPy provides a comprehensive set of mathematical functions and operations for arrays, including element-wise operations, matrix operations, linear algebra, statistical functions, and more.NumPy is heavily optimized for numerical operations, utilizing low-level libraries written in C or Fortran. This leads to significant performance improvements for large-scale computations compared to native Python or the array module.mPy supports multidimensional arrays, allowing you to work with matrices and tensors of various dimensions.

# Q4. Explain the distinctions between the empty, ones, and zeros functions.

1) numpy.empty:
This function creates a new array with uninitialized values. The values in the array are whatever happened to be in the memory location that was allocated for the array.
2) numpy.ones:
This function creates a new array with all elements initialized to 1.
3) numpy.zeros:
This function creates a new array with all elements initialized to 0.

In [6]:
import numpy as np
empty_array = np.empty((2, 3))
empty_array


array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
import numpy as np
one_array = np.ones((3,4))
one_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
import numpy as np
zero_array = np.zeros((3,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Q5. In the from function function, which is used to construct new arrays, what is the role of the callable argument?

The fromfunction function in NumPy is used to construct a new array by applying a given function to each coordinate of the array. The role of the callable argument in the fromfunction function is to define the function that will be applied to the array coordinates to determine the values of the array.

In [12]:
import numpy as np

def coordinate_sum(x,y):
    return x+y

shape =(4,3)
result = np.fromfunction(coordinate_sum,shape)
print(result)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]


# Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

NumPy performs element-wise addition between the array A and the scalar n. This means that the scalar value n is added to each element of the array A, resulting in a new array with the same shape as A but with each element increased by n.

In [14]:
import numpy as np

A = np.array([[1,2,3],
            [4,5,6]])
n=10
result = A+n
print(result)


[[11 12 13]
 [14 15 16]]


# Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

In [ ]:
It performs elment-wise addition operation and element-wise multiplication operation.

In [16]:
import numpy as np

B = np.array([[10,20,30],
             [40,50,60]])

B+=10
print(B)

[[20 30 40]
 [50 60 70]]


In [17]:
C =np.array([[12,14,18],
            [16,24,38]])

C*=4
print(C)

[[ 48  56  72]
 [ 64  96 152]]


# Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

Yes, it is possible that we can include a string of fixed length in numpy array. The dtype of any numpy array containing string values is the maximum length of any string present in the array.Once set, it will only be able to store new string having length not more than the maximum length at the time of the creation. If we try to reassign some another string value having length greater than the maximum length of the existing elements, it simply discards all the values beyond the maximum length accept upto those values which are under the limit.

# Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

The arrays you want to combine must have compatible shapes. They should either have the same shape, or one of them should have dimensions that are broadcastable to the other array's shape. Broadcasting is a concept in NumPy that allows arrays with different shapes to be combined in certain operations.

For addition and subtraction, the arrays must have the same shape or be broadcastable.

For multiplication, the arrays must have the same shape, or one of the arrays can be a scalar (single value).


It's important to note that broadcasting only works when certain conditions are met. Typically, broadcasting involves aligning the dimensions of the arrays and duplicating elements along dimensions when necessary.

# Q10. What is the best way to use a Boolean array to mask another array?

Using a Boolean array to mask another array is a powerful technique in NumPy that allows you to select elements from one array based on the corresponding values in a Boolean mask array. This process is often referred to as boolean indexing or masking.

In [20]:
import numpy as np
data = np.array([15,20,13,18])

mask = data > 16
masked_data = data[mask]
print(masked_data)

[20 18]


# Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

It's important to note that the NumPy and statistics approaches are generally more efficient and faster for calculating the standard deviation, especially when dealing with large datasets. 

In [21]:
import numpy as np            # using numpy package fastest way 
data = np.array([12,15,18,20,34,38.5])
std_dev = np.std(data)
print(std_dev)


9.83368643433829


In [22]:
import statistics   # using statistic module

data = [12,15,18,20,34,38.5]
std_dev = statistics.stdev(data)
print(std_dev)

10.77226376703925


In [31]:
def std_dev(data):                       # using function method
    mean= sum(data)/len(data)  
    squar_difference = [(x- mean) **2 for x in data]
    variance = sum(squar_difference)/ len(data)
    std_dev = variance ** 0.5
    return std_dev


data = [12,15,18,20,34,38.5]
std_dev(data)


9.83368643433829

# 12. What is the dimensionality of a Boolean mask-generated array?

The dimensionality of a Boolean mask-generated array is the same as the dimensionality of the original array for which the mask was created. In other words, if you use a Boolean mask to index or select elements from a NumPy array, the resulting masked array will have the same number of dimensions as the original array.